### ISSUE TITLE
just checking - do you know if it's compatible with Preact?

### ISSUE THREAD

**Issue by floer32** [timkindberg/zusteller#5]
Question prompted by this:

> **Using zusteller without React**
> Not possible. Use zustand. Zusteller uses hooks, and hooks must be run using react and react-dom.

I tried a quick-and-dirty way - find/replace of `'react-dom'|'react'` to `preact/compat`, then rerunning zusteller's test suite. The tests fail with a somewhat familiar error (`TypeError: Cannot read property '__H' of undefined`).

Do you happen to know if zusteller works with Preact - or, what specific incompatibility you'd anticipate?

(I'll keep trying to answer my own question in the meantime)

**Comment by timkindberg** [comment]
Hmm I haven't looked into that. Just for the record zusteller is super experimental so you'll be on your own.
