### ISSUE TITLE
something for your radar: react-tracked + zustand

### ISSUE THREAD

**Issue by floer32** [timkindberg/zusteller#6]
This is not an issue, just wanted to make sure you knew of this seemingly-related work.

https://github.com/dai-shi/react-tracked#createtrackedselector--zustand

`react-tracked` with `zustand` seems like it may allow for similar usage to `zusteller`. So maybe there is an opportunity for code-reuse or merging - on the other hand, maybe they're interesting to contrast.

**Comment by timkindberg** [comment]
That's actually what I ultimately chose to use at work 😀

**Comment by timkindberg** [comment]
To clarify we use just react-tracked alone, not with zustand.

**Comment by floer32** [comment]
@timkindberg thanks for the fast reply, much appreciated!
